title = "Agorastore"
tags = ["ts", "sass", "react", "react-spring", "storybook"]
begin = 2020-06-25
end = 2020-07-27

[fr]
subtitle = "Ventes aux enchères — Composants mobiles"
desc = """
[Agorastore](https://www.agorastore.fr/) est un site de ventes aux enchères de matériel d'occasion et de biens immobiliers. La mission consistait à rendre responsive une collection de composants [React](https://reactjs.org/), et à en implémenter quelques nouveaux (un carousel, un gestionnaire de plans, des cartes spécifiques…). La bibliothèque de composants était gérée par un [Storybook](https://storybook.js.org/). J'ai également pris certaines initiatives, comme par exemple repasser sur certains composants afin de les rendre plus UX, ou encore ajouter quelques animations avec [React Spring](https://react-spring.io/).
"""

[en]
subtitle = "Auctions — Responsive components"
desc = """
[Agorastore](https://www.agorastore.fr/) is an auction website for used equipment and real estate. The mission was to make a collection of [React](https://reactjs.org/) components responsive, and to implement some new ones (a carousel, a plan manager, mobile-specific cards, etc.). Components were managed by a [Storybook](https://storybook.js.org/). I also took some initiatives, such as refactoring some components to make them more UX, or adding some animations with [React Spring](https://react-spring.io/).
"""
