title = "Ateliers Vitalité"
tags = ["php", "sass", "sqlite"]
link = "http://www.ateliersvitalite.fr/"
begin = 2018-11-01
end = 2018-11-05

[fr]
subtitle = "Santé — Formation distancielle"
desc = """
Les Ateliers Vitalité de la [MSA](https://www.msa.fr/) sont des ateliers visant à améliorer sa qualité de vie et à préserver son capital santé. Leur besoin était d'ajouter des nouveaux modules dans une base existante développée avec PHP, Sass et SQLite. Les fiches, animations et QCM de ces nouveaux modules ont été intégrés à partir de planches graphiques fournies par [DOGMS](https://dogms.com/).
"""

[en]
subtitle = "Health — Online training app"
desc = """
Les Ateliers Vitalité from the [MSA](https://www.msa.fr/) are workshops aimed to improve quality of life and to preserve health capital of retirees people. Their need was to add new modules to an existing database developed with PHP, Sass and SQLite. The design, animations and quizzes of these new modules have been integrated from graphics provided by [DOGMS](https://dogms.com/).
"""
