title = "Camping Calamar"
tags = ["ts", "react", "sass", "gdrive"]
link = "https://soywod.github.io/camping-calamar/"
sources = "https://github.com/soywod/camping-calamar/"
begin = 2018-05-22
end = 2018-07-16

[fr]
subtitle = "Camping — Site vitrine"
desc = '''
Camping Calamar est un camping au cœur de la Corse. Ils avaient besoin de refaire leur site vitrine. L‘intégration a été effectuée avec [React.js](https://reactjs.org/), [TypeScript](https://www.typescriptlang.org/) et [Sass](https://sass-lang.com/) à partir de planches graphiques et animations fournies par [DOGMS](https://dogms.com/).
'''

[en]
subtitle = ""
desc = '''
'''
