title = "Camping Calamar"
tags = ["ts", "react", "sass", "gdrive"]
link = "https://soywod.github.io/camping-calamar/"
sources = "https://github.com/soywod/camping-calamar/"
begin = 2018-05-22
end = 2018-07-16

[fr]
subtitle = "Site vitrine - Camping"
desc = '''
Site vitrine responsive développé à partir de maquettes graphiques. L’administration se fait via Google Sheets et Google Drive.
'''

[en]
subtitle = "Showcase website - Camping"
desc = '''
'''
