title = "Cap Bien-Être"
tags = ["react", "ts", "sass", "firebase"]
link = "https://capbien-etre.fr/"
sources = "https://github.com/soywod/cap-bien-etre/"
begin = 2020-01-26
end = 2020-03-13

[fr]
subtitle = "Santé — Formation distancielle"
desc = """
Les Ateliers Cap Bien-Être de la [MSA](https://www.msa.fr/lfp) sont des ateliers visant à mieux gérer son stress et ses émotions au quotidien. Le besoin était de créer une formation en ligne à base de modules, pages et quiz. La partie serveur a été développée avec [Firebase](https://firebase.google.com/) (gestion de l'authentification et des données utilisateurs). La partie client a été développée avec [React.js](https://reactjs.org/), [TypeScript](https://www.typescriptlang.org/) et [RxJS](https://rxjs.dev/). L'intégration a été effectuée à partir de planches graphiques et animations fournies par [DOGMS](https://dogms.com/).
"""

[en]
subtitle = ""
desc = """
"""
