title = "Creator v1"
tags = ["react", "ts", "rxjs", "fabric", "sass", "prestashop"]
begin = 2020-03-04
end = 2020-06-13

[fr]
subtitle = "Signalétique — Éditeur de contenu"
desc = """
[PictoSigns](https://www.pictosigns.com/picto/) est une entreprise familiale française de signalétique. Leur projet était de permettre aux utilisateurs de créer leur plaque personnalisée en ligne et de la recevoir directement par voie postale. PictoSigns possède une boutique en ligne basée sur PrestaShop. Cette première version a été conçue en tant que plugin PrestaShop afin de facilité la production. La partie serveur s'est donc basée sur l'environnement PrestaShop (PHP/Symfony/MySQL). La partie client a été développée avec [React.js](https://reactjs.org/), [TypeScript](https://www.typescriptlang.org/), [RxJS](https://rxjs.dev/) et [Fabric.js](http://fabricjs.com/).

Cette version n'est plus accessible car elle a été remplacée par la seconde version.
"""

[en]
subtitle = "Signage — Content editor"
desc = """
[PictoSigns](https://www.pictosigns.com/picto/) is a French family-owned signage company. Their project was to allow users to create their personalized plate online and receive it directly by post. PictoSigns has an online store based on PrestaShop. This first version was designed as a PrestaShop plugin to facilitate their production chain. The backend was therefore based on the PrestaShop environment (PHP/Symfony/MySQL). The frontend was developed with [React.js](https://reactjs.org/), [TypeScript](https://www.typescriptlang.org/), [RxJS](https://rxjs.dev/) and [Fabric.js](http://fabricjs.com/).

This version is no longer accessible because it has been replaced by the second version.
"""
