title = "factAE"
tags = ["js", "react", "next", "firebase", "stripe"]
sources = "https://github.com/factae/"
begin = 2019-06-24
end = 2019-10-18

[fr]
subtitle = "Facturation — Appli web"
desc = """
FactAE est un outil de facturation dédié aux auto-entrepreneurs à un euro par mois. La partie client a été développée avec [React.js](https://reactjs.org/) et [Next.js](https://nextjs.org/). [Google Firebase](https://firebase.google.com/) a été mis en place pour l'authentification et les données utilisateurs, et [Google Cloud Functions](https://cloud.google.com/functions) a été utilisé pour la partie souscription, paiement ([Stripe](https://stripe.com/)) et génération de PDFs.

J'ai d'abord créé cet outil pour mon usage personnel, puis je me suis rendu compte que beaucoup d'autres auto-entrepreneurs de mon entourage avaient le même besoin. J'ai donc investi du temps et de l'argent pour monter cette plateforme. Je n'ai malheureusement pas réussi à faire décoller le concept. D'autres outils sont venus prendre le marché par la suite, ce qui m'a conduit à abandonner le projet. Ce fût néamoins une expérience très enrichissante !
"""

[en]
subtitle = "Invoicing — Web app"
desc = """
FactAE is an invoicing tool dedicated to French auto-entrepreneurs at one euro per month. The client part was developed with [React.js](https://reactjs.org/) and [Next.js](https://nextjs.org/). [Google Firebase](https://firebase.google.com/) has been implemented for authentication and user data, and [Google Cloud Functions](https://cloud.google.com/functions) has was used for the subscription part, payment ([Stripe](https://stripe.com/)) and generation of PDFs.

I first created this tool for my personal use, then I realized that many other self-employed people around me had the same need. So I invested time and money to set up this platform. Unfortunately, I didn't manage to get the concept off the ground. Other tools came to take over the market afterwards, which led me to abandon the project. It was nevertheless a very rewarding experience!
"""
