title = "Island Tours"
tags = ["ts", "angular", "less"]
link = "https://www.islandtours.fr/"
sources = "https://github.com/soywod/island-tours/"
begin = 2016-11-06
end = 2016-11-09

[fr]
subtitle = "Voyage — Formulaire dynamique"
desc = """
Island Tours est une agence de voyage autour de l'Island. Il avait besoin d'un formulaire interactif en lien avec une newsletter.
"""

[en]
subtitle = ""
desc = """
"""
