title = "Sigma Search"
tags = ["ts", "react", "stylus"]
link = "https://sigma-search.com/"
sources = "https://github.com/soywod/sigma-search/"
begin = 2018-10-01
end = 2018-10-20

[fr]
subtitle = "Recrutement — Site vitrine"
desc = """
Sigma Search est une boîte de recrutement internationale. Ils avaient besoin de refaire leur site vitrine. L'intégration a été effectuée avec [React.js](https://reactjs.org/), [TypeScript](https://www.typescriptlang.org/) et [Stylus](https://stylus-lang.com/) à partir de planches graphiques et animations fournies par [DOGMS](https://dogms.com/).
"""

[en]
subtitle = ""
desc = """
"""
