title = "Smart Services"
tags = ["html", "css", "js", "jquery", "fullpage"]
sources = "https://github.com/soywod/smart-services/"
begin = 2016-09-15
end = 2016-09-20

[fr]
subtitle = "Conseil — Site vitrine"
desc = """
Smart Services est un cabinet de conseil. Ils avaient besoin d'un site vitrine sous forme de diaporama. Le site a été développé avec [fullPage.js](https://alvarotrigo.com/fullPage/) et [jQuery](https://jquery.com/).
"""

[en]
subtitle = "Consulting — Showcase website"
desc = """
Smart Services is a consulting firm. They needed a showcase site in the form of a slideshow. The site was developed with [fullPage.js](https://alvarotrigo.com/fullPage/) and [jQuery](https://jquery.com/).
"""
