title = "Smart Services"
tags = ["html", "css", "js", "jquery", "fullpage"]
sources = "https://github.com/soywod/smart-services/"
begin = 2016-09-15
end = 2016-09-20

[fr]
subtitle = "Appli web - Cabinet de conseil"
desc = '''
Diaporama en ligne développé en javascript. Le projet n’est plus en ligne, mais le code est toujours disponible.
'''

[en]
subtitle = "Web app - "
desc = '''
'''
