extends:
  - plugin:react/recommended
  - eslint:recommended
  - prettier

plugins:
  - react
  - react-hooks

parser: babel-eslint

parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  node: true

rules:
  arrow-parens:
    - error
    - as-needed
  no-console: 0
  prefer-const: 0
  react-hooks/exhaustive-deps: warn
  react-hooks/rules-of-hooks: error
  react/display-name: off
  react/no-unescaped-entities: 0
  react/prop-types: off
