[build]
command = "yarn build"
publish = "build"

[[redirects]]
  from = "*"
  to = "/fr/:splat"
  status = 301
  force = false
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "*"
  to = "/en/:splat"
  status = 301
  force = false
