company = "Afrimarket"
companyLink = "https://afrimarket.fr/"
tags = ["php", "laravel", "js", "angular"]
begin = 2016-02-22
end = 2016-04-15

[fr]
title = "Lead développeur"
desc = """
Afrimarket est une startup spécialisée dans la vente de biens et de services en Afrique de l'Ouest. La mission consistait à refondre leur back-end avec [AngularJS](https://angularjs.org/) et [Laraval](https://laravel.com/). J'ai également eu l'occasion de corriger quelques bugs sur leur boutique en ligne PrestaShop.
"""

[en]
title = ""
desc = """
"""
