company = "Colas"
companyLink = "https://www.colas.com/"
subcompany = "Strategy Partner"
tags = []
begin = 2017-11-01
end = 2018-09-22

[fr]
title = "Développeur web"
desc = """
"""

[en]
title = "Web developer"
desc = """
"""
