company = "Colas"
companyLink = "https://www.colas.com/"
subcompany = "Strategy Partner"
tags = ["js", "ts", "node", "express"]
begin = 2017-11-01
end = 2018-09-22

[fr]
title = "Ingénieur R&D"
desc = """
Colas est une entreprise française de travaux publics. La mission consistait à développer une interface au dessus de leur CRM Serena. Cette interface a été utilisée par plusieurs sous-projets qui m'ont été également attribués par la suite :

- un script [Node.js](https://nodejs.org/) de synchronisation de données avec un [Microsoft SQL Server](https://www.microsoft.com/sql-server/)
- une API JSON de gestion de commandes

La plupart des outils ont été développés avec [TypeScript](https://www.typescriptlang.org/) et [Node.js](https://nodejs.org/). 
"""

[en]
title = "R&D engineer"
desc = """
Colas is a French public works company. The mission was to develop an interface for their CRM Serena. This interface was used by several sub-projects which were also assigned to me later:

- a [Node.js](https://nodejs.org/) script for synchronizing data with a [Microsoft SQL Server](https://www.microsoft.com/sql-server/)
- a JSON order management API

Most of the tools were developed with [TypeScript](https://www.typescriptlang.org/) and [Node.js](https://nodejs.org/).
"""
