company = "L'École Multimédia"
companyLink = "https://www.ecole-multimedia.com/"
tags = ["js", "angular"]
begin = 2016-07-27
end = 2016-07-29

[fr]
title = "Formateur"
desc = '''
'''

[en]
title = ""
desc = '''
'''
