company = "L'École Multimédia"
companyLink = "https://www.ecole-multimedia.com/"
tags = ["js", "angular"]
begin = 2016-08-17
end = 2016-08-26

[fr]
title = "Formateur"
desc = """
L'École Multimédia est une école proposant de nombreuses formations aux métiers du numérique. J'ai eu l'occasion d'y donner des cours d'initiation au framework [AngularJS](https://angularjs.org/).
"""

[en]
title = "Former"
desc = """
L'École Multimédia is a school offering numerous training courses in digital professions. I had the opportunity to give introductory lessons to the framework [AngularJS](https://angularjs.org/).
"""