company = "L‘École Multimédia"
link = "https://www.ecole-multimedia.com/"
tags = ["js", "angular"]
begin = 2016-06-01
end = 2016-06-06

[fr]
title = "Formateur"
desc = '''
'''

[en]
title = ""
desc = '''
'''
