company = "L'École Multimédia"
companyLink = "https://www.ecole-multimedia.com/"
tags = ["js", "angular"]
begin = 2016-08-17
end = 2016-08-26

[fr]
title = "Formateur"
desc = '''
'''

[en]
title = ""
desc = '''
'''
