company = "Fluo"
companyLink = "https://www.fluo.com/"
subcompany = "SFEIR"
subcompanyLink = "https://www.sfeir.com/"
tags = ["js", "flow", "react", "react-native"]
begin = 2017-01-09
end = 2017-11-30

[fr]
title = "Ingénieur d'études et développement"
desc = """
Fluo est le spécialiste de la distribution d'assurance qui permet de comparer les garanties avec les tarifs des assurances. La mission a été très variée. J'ai eu l'occasion d'intervenir sur de nombreux sujets :
- Développement d'un système de hook au sein de l'API principale avec [JavaScript](https://developer.mozilla.org/docs/Web/JavaScript) et [Flow](https://flow.org/)
- Amélioration d'un composant [React](https://reactjs.org/) de comparaison de garanties d'assurances
- Corrections de bugs et déploiement (Android et iOS) de l'application mobile développée avec [React Native](https://reactnative.dev/) et [Flow](https://flow.org/)
- Intégration d'une solution d'authentification SaaS ([Okta](https://www.okta.com/))
"""

[en]
title = "R&D engineer"
desc = """
Fluo is the insurance distribution specialist that allows you to compare guarantees with insurance rates. The mission was very varied. I had the opportunity to:
- develop a hook system within the main API with [JavaScript](https://developer.mozilla.org/docs/Web/JavaScript) and [Flow](https://flow.org/)
- improve a [React](https://reactjs.org/) component for comparing insurance guarantees
- fix bugs and deploy (Android and iOS) the mobile application developed with [React Native](https://reactnative.dev/) and [Flow](https://flow.org/)
- integrate a SaaS authentication solution ([Okta](https://www.okta.com/))
"""
