company = "Swan"
companyLink = "https://www.swan.io/"
tags = ["ts", "fp-ts", "node", "nest", "graphql", "apollo", "sequelize"]
begin = 2021-08-30
end = 2021-11-30

[fr]
title = "Ingénieur R&D"
desc = """
Swan est une plateforme de [Banking-as-a-Service](https://fr.wikipedia.org/wiki/Banking-as-a-Service). Lors de cette mission, j'ai été chargé d'améliorer et de sécuriser l'API d'intégration des nouveaux clients (onboarding). J'ai également participé à l'amélioration de l'API de création de projets. Swan utilisait beaucoup [fp-ts](https://gcanti.github.io/fp-ts/), et ça a été une très belle découverte pour ma part. Cette librairie permet d'utiliser, en [TypeScript](https://www.typescriptlang.org/), des concepts fonctionnels tels que les [applicatives](https://en.wikipedia.org/wiki/Applicative_functor) ou les [monades](https://fr.wikipedia.org/wiki/Monade_(informatique)). Ça a été une excellente opportunité pour moi de mettre en pratique mes connaissances dans ce domaine : réécriture de certaines parties de l'API en mode plus fonctionnel, présentation de concepts fonctionnels devant toute l'équipe tech, mise en place d'un validateur de données basé sur les applicatives…
"""

[en]
title = "R&D engineer"
desc = """
Swan is a [Banking-as-a-Service](https://fr.wikipedia.org/wiki/Banking-as-a-Service) platform. As a part of their team, I was in charge of improving and securing the API for new customers onboarding. I also participated in improving the project creation API. Swan used [fp-ts](https://gcanti.github.io/fp-ts/) a lot, and it was a great discovery for me. This library allows the use, in [TypeScript](https://www.typescriptlang.org/), of functional concepts such as [applicatives](https://en.wikipedia.org/wiki/Applicative_functor) or [monads](https://en.wikipedia.org/wiki/Monad_(functional_programming)). It was an excellent opportunity for me to put my knowledge into practice in this area: rewriting parts of the API in a more functional way, introducing functional concepts to the tech team, developing a data validator using applicatives…
"""
