company = "The green data"
companyLink = "https://www.thegreendata.com/"
tags = ["js", "python", "pyodide", "wa"]
begin = 2020-11-16
end = 2021-01-10

[fr]
title = "Ingénieur R&D"
desc = """
The green data est une plateforme décisionnelle de l'agriculture régénératrice. L'objectif de la mission était de faire fonctionner un simulateur écrit en Python par des data scientists dans un navigateur web grâce à [Pyodide](https://github.com/pyodide/pyodide/), un interpréteur Python basé sur la technologie [WebAssembly](https://webassembly.org/).
"""

[en]
title = "R&D engineer"
desc = """
The green data is a decision-making platform for regenerative agriculture. The objective of the mission was to run a simulator written in Python by data scientists in a web browser using [Pyodide](https://github.com/pyodide/pyodide/), a Python interpreter based on [WebAssembly](https://webassembly.org/) technology.
"""
