company = "The green data"
companyLink = "https://www.thegreendata.com/"
tags = ["js", "ts", "react", "mui", "blockchain"]
begin = 2020-11-16
end = 2021-01-10

[fr]
title = "Développeur web"
desc = """
"""

[en]
title = "Web developer"
desc = """
"""
