company = "Tokeny"
companyLink = "https://tokeny.com/"
tags = ["js", "ts", "react", "mui", "blockchain"]
begin = 2018-09-25
end = 2019-02-28

[fr]
title = "Développeur web"
desc = """
"""

[en]
title = "Web developer"
desc = """
"""
