company = "Whaller"
link = "https://waller.com/"
tags = ["php", "codeigniter", "js", "jquery", "docker"]
begin = 2015-10-12
end = 2016-02-20

[fr]
title = "Développeur"
desc = '''
Corrections de bugs back-end sur CodeIgniter (PHP) et sur un front-end en jQuery. Développement dun lecteur de flux RSS en jQuery. Développement dun gestionnaire de fichiers en jQuery.
'''

[en]
title = ""
desc = '''
'''
