company = "Whaller"
companyLink = "https://whaller.com/"
tags = ["php", "codeigniter", "js", "jquery", "docker"]
begin = 2015-10-12
end = 2016-02-20

[fr]
title = "Développeur"
desc = """
Whaller est une plateforme qui permet aux utilisateurs de créer leurs propres réseaux sociaux et collaboratifs sécurisés. Lors de cette mission j'ai eu l'occasion :
- d'ajouter des nouvelles fonctionnalités et de corriger des bugs liés au backend en PHP ([CodeIgniter](https://codeigniter.com/))
- de développer un lecteur de flux RSS en PHP et jQuery
- de développer un gestionnaire de fichiers (*alla* [Dropbox](https://www.dropbox.com/home)) en PHP et jQuery
"""

[en]
title = "Developer"
desc = """
Whaller is a platform that permits to its users to creat their own secure social networks. I had an occasion to:
- add new features and fix bugs related to the PHP backend ([CodeIgniter](https://codeigniter.com/))
- develop a RSS feed reader in PHP and jQuery
- develop a [Dropbox](https://www.dropbox.com/home)-like file manager in PHP and jQuery
"""
