company = "Whaller"
companyLink = "https://whaller.com/"
tags = ["php", "codeigniter", "js", "jquery", "docker"]
begin = 2015-09-15
end = 2015-10-09

[fr]
title = "Stagiaire"
desc = """
Whaller est une plateforme qui permet aux utilisateurs de créer leurs propres réseaux sociaux et collaboratifs sécurisés. Durant ce stage j'ai appris à utiliser [CodeIgniter](https://codeigniter.com/) et [jQuery](https://jquery.com/), et à mettre en pratique ces nouveaux acquis en corrigeant des bugs et en ajoutant des nouvelles fonctionnalités.
"""

[en]
title = ""
desc = """
"""
