company = "Wincor Nixdorf"
link = "https://www.dieboldnixdorf.com/"
tags = ["c", "c++", "java", "php", "js", "node"]
begin = 2012-01-01
end = 2015-09-10

[fr]
title = "Technicien test support logiciel"
desc = '''
Développement doutils daide au diagnostic pour logiciels dencaissement. Développement de scripts dinstallation de logiciels dencaissement. Support de niveau 1, 2 et 3 (matériel et logiciel).
'''

[en]
title = ""
desc = '''
'''
