company = "Wincor Nixdorf"
companyLink = "https://www.dieboldnixdorf.com/"
tags = ["vb.net", "vba", "quick test pro"]
begin = 2010-04-01
end = 2010-06-01

[fr]
title = "Stagiaire"
desc = """
Wincor Nixdorf est un fournisseur de solutions pour la grande distribution. Au sein de leur équipe QA, j'ai participé à l'automatisation des tests d'intégration des logiciels d'encaissement (notamment Picard et Super U). J'ai appris à coder en Visual Basic et à utiliser le logiciel Quick Test Pro.
"""

[en]
title = "Trainee"
desc = """
Wincor Nixdorf is a solution provider for large scale (wholesale) retail. As a part of their QA team, I participated in automatisation of integration tests of check cashing software (in particular Super U and Picard). I learned to code in Visual Basic and to use Quick Test Pro software.
"""
