company = "Wincor Nixdorf"
companyLink = "https://www.dieboldnixdorf.com/"
tags = ["c", "c++", "java", "php", "js", "node"]
begin = 2012-01-01
end = 2015-09-10

[fr]
title = "Technicien test et support logiciel"
desc = """
Wincor Nixdorf est un fournisseur de solutions pour la grande distribution. J'ai eu l'occasion :
- de développer des outils d'aide au diagnostic pour logiciels d'encaissement
- de développer des scripts d'installation de logiciels d'encaissement
- d'effectuer le support materiel et logiciel de systèmes d'encaissement (Picard, Castorama, Bricorama)
"""

[en]
title = "Software testing technician"
desc = """
Wincor Nixdorf is a solution provider for large scale (wholesale) retail. There, I had an occasion to:
- develop diagnostic tools for check cashing software
- develop installation scripts for check cashing software
- provide hardware and software support of cash checking systems (Picard, Castorama, Bricorama)
"""
